### ISSUE TITLE
What is the point of user: ${CURRENT_UID} in database service

### ISSUE THREAD

**Issue by wyattbiker** [robertsaupe/docker-compose-lamp#2]
It's using my current logged in ID when I use the build.sh
`CURRENT_UID=$(id -u):$(id -g) docker-compose up -d --build`

Just trying to figure out why use that id.  Thanks

```yml
database:
    build:
      context: "./bin/${DATABASE}"
    container_name: '${COMPOSE_PROJECT_NAME}-${DATABASE}'
    restart: 'always'
    ports:
      - "127.0.0.1:${HOST_MACHINE_MYSQL_PORT}:3306"
    user: ${CURRENT_UID}
    volumes: 
      - ${MYSQL_INITDB_DIR-./config/initdb}:/docker-entrypoint-initdb.d
      - ${MYSQL_DATA_DIR-./data/mysql}:/var/lib/mysql
      - ${MYSQL_LOG_DIR-./logs/mysql}:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
```
